-- Product table
ALTER TABLE Product
DROP CONSTRAINT IF EXISTS FK_Product_Brand;

ALTER TABLE Product
ADD CONSTRAINT FK_Product_Brand
FOREIGN KEY (BrandID) REFERENCES Brand(BrandID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- ClothingItem table
ALTER TABLE ClothingItem
DROP CONSTRAINT IF EXISTS FK_ClothingItem_Product;

ALTER TABLE ClothingItem
ADD CONSTRAINT FK_ClothingItem_Product
FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
ON DELETE CASCADE
ON UPDATE CASCADE;

-- AccessoryItem table
ALTER TABLE AccessoryItem
DROP CONSTRAINT IF EXISTS FK_AccessoryItem_Product;

ALTER TABLE AccessoryItem
ADD CONSTRAINT FK_AccessoryItem_Product
FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
ON DELETE CASCADE
ON UPDATE CASCADE;

-- SustainabilityMetric table
ALTER TABLE SustainabilityMetric
DROP CONSTRAINT IF EXISTS FK_SustainabilityMetric_Product;

ALTER TABLE SustainabilityMetric
ADD CONSTRAINT FK_SustainabilityMetric_Product
FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE SustainabilityMetric
DROP CONSTRAINT IF EXISTS FK_SustainabilityMetric_Brand;

ALTER TABLE SustainabilityMetric
ADD CONSTRAINT FK_SustainabilityMetric_Brand
FOREIGN KEY (BrandID) REFERENCES Brand(BrandID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- Inventory table
ALTER TABLE Inventory
DROP CONSTRAINT IF EXISTS FK_Inventory_Product;

ALTER TABLE Inventory
ADD CONSTRAINT FK_Inventory_Product
FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- UserActivity table
ALTER TABLE UserActivity
DROP CONSTRAINT IF EXISTS FK_UserActivity_User;

ALTER TABLE UserActivity
ADD CONSTRAINT FK_UserActivity_User
FOREIGN KEY (UserID) REFERENCES "User"(UserID)
ON DELETE CASCADE
ON UPDATE CASCADE;

-- Cart table
ALTER TABLE Cart
DROP CONSTRAINT IF EXISTS FK_Cart_User;

ALTER TABLE Cart
ADD CONSTRAINT FK_Cart_User
FOREIGN KEY (UserID) REFERENCES "User"(UserID)
ON DELETE CASCADE
ON UPDATE CASCADE;

-- CartItem table
ALTER TABLE CartItem
DROP CONSTRAINT IF EXISTS FK_CartItem_Cart;

ALTER TABLE CartItem
ADD CONSTRAINT FK_CartItem_Cart
FOREIGN KEY (CartID) REFERENCES Cart(CartID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE CartItem
DROP CONSTRAINT IF EXISTS FK_CartItem_Product;

ALTER TABLE CartItem
ADD CONSTRAINT FK_CartItem_Product
FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- Wishlist table
ALTER TABLE Wishlist
DROP CONSTRAINT IF EXISTS FK_Wishlist_User;

ALTER TABLE Wishlist
ADD CONSTRAINT FK_Wishlist_User
FOREIGN KEY (UserID) REFERENCES "User"(UserID)
ON DELETE CASCADE
ON UPDATE CASCADE;

-- WishlistItem table
ALTER TABLE WishlistItem
DROP CONSTRAINT IF EXISTS FK_WishlistItem_Wishlist;

ALTER TABLE WishlistItem
ADD CONSTRAINT FK_WishlistItem_Wishlist
FOREIGN KEY (WishlistID) REFERENCES Wishlist(WishlistID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE WishlistItem
DROP CONSTRAINT IF EXISTS FK_WishlistItem_Product;

ALTER TABLE WishlistItem
ADD CONSTRAINT FK_WishlistItem_Product
FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- Review table
ALTER TABLE Review
DROP CONSTRAINT IF EXISTS FK_Review_User;

ALTER TABLE Review
ADD CONSTRAINT FK_Review_User
FOREIGN KEY (UserID) REFERENCES "User"(UserID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Review
DROP CONSTRAINT IF EXISTS FK_Review_Product;

ALTER TABLE Review
ADD CONSTRAINT FK_Review_Product
FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- Outfit table
ALTER TABLE Outfit
DROP CONSTRAINT IF EXISTS FK_Outfit_User;

ALTER TABLE Outfit
ADD CONSTRAINT FK_Outfit_User
FOREIGN KEY (UserID) REFERENCES "User"(UserID)
ON DELETE CASCADE
ON UPDATE CASCADE;


-- OutfitItem table
ALTER TABLE OutfitItem
DROP CONSTRAINT IF EXISTS FK_OutfitItem_Outfit;

ALTER TABLE OutfitItem
ADD CONSTRAINT FK_OutfitItem_Outfit
FOREIGN KEY (OutfitID) REFERENCES Outfit(OutfitID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE OutfitItem
DROP CONSTRAINT IF EXISTS FK_OutfitItem_Product;

ALTER TABLE OutfitItem
ADD CONSTRAINT FK_OutfitItem_Product
FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- Order table
ALTER TABLE "Order"
DROP CONSTRAINT IF EXISTS FK_Order_User;

ALTER TABLE "Order"
ADD CONSTRAINT FK_Order_User
FOREIGN KEY (UserID) REFERENCES "User"(UserID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- OrderItem table
ALTER TABLE OrderItem
DROP CONSTRAINT IF EXISTS FK_OrderItem_Order;

ALTER TABLE OrderItem
ADD CONSTRAINT FK_OrderItem_Order
FOREIGN KEY (OrderID) REFERENCES "Order"(OrderID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE OrderItem
DROP CONSTRAINT IF EXISTS FK_OrderItem_Product;

ALTER TABLE OrderItem
ADD CONSTRAINT FK_OrderItem_Product
FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- Payment table
ALTER TABLE Payment
DROP CONSTRAINT IF EXISTS FK_Payment_Order;

ALTER TABLE Payment
ADD CONSTRAINT FK_Payment_Order
FOREIGN KEY (OrderID) REFERENCES "Order"(OrderID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- Return table
ALTER TABLE "Return"
DROP CONSTRAINT IF EXISTS FK_Return_Order;

ALTER TABLE "Return"
ADD CONSTRAINT FK_Return_Order
FOREIGN KEY (OrderID) REFERENCES "Order"(OrderID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE "Return"
DROP CONSTRAINT IF EXISTS FK_Return_Product;

ALTER TABLE "Return"
ADD CONSTRAINT FK_Return_Product
FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- Shipment table
ALTER TABLE Shipment
DROP CONSTRAINT IF EXISTS FK_Shipment_Order;

ALTER TABLE Shipment
ADD CONSTRAINT FK_Shipment_Order
FOREIGN KEY (OrderID) REFERENCES "Order"(OrderID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- LoyaltyProgram table
ALTER TABLE LoyaltyProgram
ADD CONSTRAINT FK_LoyaltyProgram_User
FOREIGN KEY (UserID) REFERENCES [User](UserID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE LoyaltyProgram
ADD CONSTRAINT FK_LoyaltyProgram_Order
FOREIGN KEY (OrderID) REFERENCES [Order](OrderID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

